"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowUpRight,Check,CalendarDays,HeartHandshake,LogOut,Save,Trash2,Trophy} from "lucide-react";
import {getSupabaseBrowser} from "../../lib/supabase/client";
import {keepLatestFive,validateStablefordScore} from "../../lib/domain";
type Score={id:string;date:string;score:number};
type Charity={id:string;name:string;slug:string;description:string};
export default function Dashboard(){
 const router=useRouter();
 const[scores,setScores]=useState<Score[]>([]);
 const[charities,setCharities]=useState<Charity[]>([]);
 const[summary,setSummary]=useState<any>(null);
 const[score,setScore]=useState("");
 const[date,setDate]=useState("");
 const[editingId,setEditingId]=useState<string|null>(null);
 const[charityId,setCharityId]=useState("");
 const[charityPercent,setCharityPercent]=useState(10);
 const[message,setMessage]=useState("");
 const[busy,setBusy]=useState(false);
 const ordered=useMemo(()=>keepLatestFive(scores.map(s=>({date:s.date,score:s.score}))).map(x=>scores.find(s=>s.date===x.date)!).filter(Boolean),[scores]);
 useEffect(()=>{const supabase=getSupabaseBrowser();if(!supabase){setMessage("Authentication is not configured yet.");return}supabase.auth.getUser().then(async({data})=>{if(!data.user){router.replace("/login");return}const[a,b,c]=await Promise.all([fetch("/api/dashboard/summary"),fetch("/api/charities"),fetch("/api/preferences")]);if(a.status===402){router.replace("/pricing");return}if(a.ok){const x=await a.json();setSummary(x);setScores((x.scores??[]).map((s:any)=>({id:s.id,date:s.score_date,score:s.score})))}if(b.ok){const x=await b.json();setCharities(x.charities??[])}if(c.ok){const x=await c.json();if(x.preference){setCharityId(x.preference.charity_id||"");setCharityPercent(x.preference.charity_percent||10)}}})},[router]);
 async function saveScore(){const n=Number(score);if(!date||!validateStablefordScore(n)){setMessage("Enter a valid Stableford score between 1 and 45.");return}setBusy(true);const url=editingId?"/api/scores/"+editingId:"/api/scores";const method=editingId?"PATCH":"POST";const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify({score:n,scoreDate:date})});const b=await r.json().catch(()=>({}));if(r.ok){const s=b.score;setScores(prev=>editingId?prev.map(x=>x.id===editingId?{id:s.id,date:s.score_date,score:s.score}:x):keepLatestFive([...prev,{id:s.id,date:s.score_date,score:s.score}].map(x=>({date:x.date,score:x.score,id:x.id}))));setEditingId(null);setScore("");setDate("");setMessage("Score saved.")}else setMessage(b.error||"Unable to save score.");setBusy(false)}
 async function removeScore(id:string){setBusy(true);const r=await fetch("/api/scores/"+id,{method:"DELETE"});if(r.ok){setScores(prev=>prev.filter(x=>x.id!==id));setMessage("Score removed.")}else setMessage("Unable to remove score.");setBusy(false)}
 async function editScore(s:Score){setEditingId(s.id);setScore(String(s.score));setDate(s.date);window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
 async function savePreference(){if(!charityId){setMessage("Choose a charity first.");return}setBusy(true);const r=await fetch("/api/preferences",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({charityId,charityPercent})});const b=await r.json().catch(()=>({}));setMessage(r.ok?"Charity preference saved.":b.error||"Unable to save charity preference.");setBusy(false)}
 async function signOut(){const supabase=getSupabaseBrowser();if(supabase)await supabase.auth.signOut();router.push("/login")}
 return <main className="min-h-screen bg-[#f6f3ea] text-[#12201d]">
 <header className="sticky top-0 z-40 border-b border-black/5 bg-[#f6f3ea]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><a href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#12201d] text-sm font-semibold text-white">D</span><span className="text-xs font-semibold uppercase tracking-[.24em]">Member space</span></a><div className="flex items-center gap-2"><a href="/pricing" className="hidden rounded-full px-4 py-2 text-sm text-black/55 hover:bg-black/5 sm:block">Membership</a><a href="/winner" className="rounded-full bg-[#12201d] px-4 py-2 text-sm font-medium text-white">Winner proof</a><button onClick={signOut} aria-label="Sign out" className="grid size-10 place-items-center rounded-full border border-black/8 bg-white/60 text-black/45 hover:bg-white"><LogOut size={16}/></button></div></div></header>
 <section className="mx-auto max-w-7xl px-5 pb-10 pt-10 md:px-8 md:pt-14"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="text-xs font-semibold uppercase tracking-[.22em] text-[#d58f58]">Your member dashboard</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.035em] md:text-6xl">Your game, your impact.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-black/50">Everything important in one quiet place — scores, subscription, cause, draw participation and winnings.</p></div><a href="/draw" className="inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">See draw rules <ArrowUpRight size={15}/></a></div>
 <div className="mt-9 grid gap-4 lg:grid-cols-4">
 <div className="rounded-[1.6rem] bg-[#12201d] p-6 text-white"><div className="text-[10px] uppercase tracking-[.18em] text-white/40">Subscription</div><div className="mt-3 text-2xl font-semibold">{summary?.subscription?.status==="active"?"Active":"Not active"}</div><div className="mt-1 text-xs text-white/45">{summary?.subscription?.renewal_date?"Renews "+summary.subscription.renewal_date:"Activate a plan to enter draws"}</div></div>
 <div className="rounded-[1.6rem] border border-black/7 bg-white/65 p-6"><div className="text-[10px] uppercase tracking-[.18em] text-black/35">Your cause</div><div className="mt-3 flex items-center gap-2 text-2xl font-semibold"><HeartHandshake size={20} className="text-[#567261]"/>{summary?.preference?.charity_percent??charityPercent}%</div><div className="mt-1 text-xs text-black/45">{summary?.preference?.charities?.name??"Choose a charity"}</div></div>
 <div className="rounded-[1.6rem] border border-black/7 bg-white/65 p-6"><div className="text-[10px] uppercase tracking-[.18em] text-black/35">Draws entered</div><div className="mt-3 text-2xl font-semibold">{summary?.participation?.drawsEntered??0}</div><div className="mt-1 text-xs text-black/45">{summary?.participation?.upcomingDraws?.length??0} published draws tracked</div></div>
 <div className="rounded-[1.6rem] bg-[#d9e5dc] p-6"><div className="text-[10px] uppercase tracking-[.18em] text-black/35">Winnings</div><div className="mt-3 flex items-center gap-2 text-2xl font-semibold"><Trophy size={19} className="text-[#8b5e3f]"/>£{(summary?.winnings?.total??0).toFixed(2)}</div><div className="mt-1 text-xs text-black/45">Current prize total</div></div>
 </div></section>
 <section className="mx-auto max-w-7xl px-5 pb-24 md:px-8"><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
 <section className="rounded-[2rem] border border-black/7 bg-white/70 p-6 md:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="text-xs font-semibold uppercase tracking-[.2em] text-[#d58f58]">Performance</div><h2 className="mt-2 text-2xl font-semibold">Latest five scores</h2><p className="mt-1 text-sm text-black/45">Edit or delete any entry. The oldest rolls off automatically when a sixth is added.</p></div><div className="rounded-full bg-[#f6f3ea] px-3 py-1.5 text-xs text-black/45">{ordered.length}/5 stored</div></div>
 <div className="mt-7 grid gap-3">{ordered.map((s,i)=><div key={s.id} className="flex items-center justify-between rounded-2xl border border-black/7 bg-[#f6f3ea]/80 p-4"><div className="flex items-center gap-4"><div className="grid size-11 place-items-center rounded-xl bg-[#12201d] text-sm font-semibold text-white">{s.score}</div><div><div className="flex items-center gap-2 text-sm font-medium">{s.date}{i===0&&<span className="rounded-full bg-[#d9e5dc] px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[.12em] text-[#567261]">Latest</span>}</div><div className="mt-1 text-xs text-black/40">Stableford score</div></div></div><div className="flex items-center gap-1"><button onClick={()=>editScore(s)} className="rounded-xl p-2 text-xs text-black/45 hover:bg-white hover:text-black">Edit</button><button onClick={()=>removeScore(s.id)} className="rounded-xl p-2 text-black/35 hover:bg-red-50 hover:text-red-600" aria-label={"Delete score "+s.date}><Trash2 size={15}/></button></div></div>)}</div>
 </section>
 <aside className="rounded-[2rem] bg-[#12201d] p-6 text-white md:p-8"><div className="text-xs font-semibold uppercase tracking-[.2em] text-[#d6a57e]">{editingId?"Edit round":"Add a round"}</div><h2 className="mt-2 text-2xl font-semibold">Keep your form current.</h2><p className="mt-2 text-sm leading-6 text-white/50">Enter a Stableford score from 1–45 and the date you played.</p><div className="mt-7 grid gap-3"><input value={date} onChange={e=>setDate(e.target.value)} className="rounded-2xl border border-white/10 bg-white/7 p-3.5 text-white outline-none" type="date"/><input value={score} onChange={e=>setScore(e.target.value)} className="rounded-2xl border border-white/10 bg-white/7 p-3.5 text-white outline-none" type="number" min="1" max="45" placeholder="Stableford 1–45"/><div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={saveScore} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white p-3.5 text-sm font-medium text-[#12201d] disabled:opacity-50"><Save size={16}/>{busy?"Saving…":"Save score"}</button><button disabled={!editingId||busy} onClick={()=>{setEditingId(null);setScore("");setDate("")}} className="rounded-2xl border border-white/10 p-3.5 text-sm text-white/70 disabled:opacity-30">Cancel</button></div>{message&&<div className="rounded-2xl border border-white/10 bg-white/6 p-3 text-xs text-white/70">{message}</div>}</div>
 <div className="mt-8 border-t border-white/10 pt-6"><div className="text-xs uppercase tracking-[.18em] text-white/35">Cause settings</div><select value={charityId} onChange={e=>setCharityId(e.target.value)} className="mt-3 w-full rounded-2xl border border-white/10 bg-white/7 p-3.5 text-sm text-white"><option value="" className="text-black">Choose a charity</option>{charities.map(c=><option key={c.id} value={c.id} className="text-black">{c.name}</option>)}</select><div className="mt-3 flex items-center gap-3"><input aria-label="Charity contribution percentage" type="range" min="10" max="100" step="5" value={charityPercent} onChange={e=>setCharityPercent(Number(e.target.value))} className="w-full"/><span className="w-12 text-right text-sm font-semibold">{charityPercent}%</span></div><button onClick={savePreference} disabled={busy||!charityId} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/6 p-3 text-sm text-white/80 disabled:opacity-40"><Check size={15}/>Save cause</button></div></aside>
 </div>
 <section className="mt-5 rounded-[2rem] border border-black/7 bg-white/70 p-6 md:p-8"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.2em] text-[#d58f8f]">Participation</div><h2 className="mt-2 text-2xl font-semibold">Your draw history</h2></div><a href="/draw" className="text-sm underline underline-offset-4">Rules</a></div><div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(summary?.winnings?.results??[]).map((r:any)=><div key={r.id} className="rounded-2xl border border-black/7 bg-[#f6f3ea] p-4"><div className="flex items-center justify-between"><span className="text-xs text-black/40">{r.draws?.month??"Draw"}</span><span className="rounded-full bg-[#d9e5dc] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-[#567261]">{r.winner_status}</span></div><div className="mt-4 flex items-end justify-between"><div><div className="text-2xl font-semibold">{r.matched_numbers}/5</div><div className="mt-1 text-xs text-black/45">Matched numbers</div></div><div className="text-right"><div className="text-lg font-semibold">£{Number(r.prize_amount||0).toFixed(2)}</div><div className="text-xs text-black/45">Prize</div></div></div></div>)}</div>{(summary?.winnings?.results?.length??0)===0&&<div className="rounded-2xl bg-[#f6f3ea] p-6 text-sm text-black/45">Your published draw results will appear here.</div>}</section>
 </section></main>
}